version: "3.9"

services:
  redis:
    image: redis:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    networks:
      - coinswarmnet
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.60.101:12201"
        tag: "redis"

  worker:
    image: minhcong2302/worker:coinswarm
    deploy:
      replicas: 15
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
    networks:
      - coinswarmnet
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.60.101:12201"
        tag: "worker"

  rng:
    image: minhcong2302/rng:coinswarm
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
    ports:
      - "8001:80"
    networks:
      - coinswarmnet
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.60.101:12201"
        tag: "rng"

  hasher:
    image: minhcong2302/hasher:coinswarm
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
    ports:
      - "8002:80"
    networks:
      - coinswarmnet
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.60.101:12201"
        tag: "hasher"

  webui:
    image: minhcong2302/webui:coinswarm
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - coinswarmnet
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.60.101:12201"
        tag: "webui"

networks:
  coinswarmnet:
    external: true
