version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitornet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitornet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          
  # InfluxDB: Lưu trữ dữ liệu metrics từ Prometheus
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=prometheus-metrics
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-secret-token
    networks:
      - monitornet
    deploy:
      replicas: 1

networks:
  monitornet:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  influxdb_data:

configs:
  prometheus_config:
    file: ./prometheus.yml
