global:
  scrape_interval: 15s  # Tần suất thu thập dữ liệu

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '192.168.60.104:9100'
          - '192.168.60.105:9100'
          - '192.168.60.106:9100'
          - '192.168.60.107:9100'
          - '192.168.60.108:9100'
          - '192.168.60.109:9100'
          - '192.168.60.110:9100'

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
